db:
  driver:   postgres
  host:     localhost
  port:     5432
  database: postgres
  username: postgres
  password: test
  detail-log:     true
  max-open-conns: 100
  max-idle-conns: 10
server:
  port: :8888