db:
  driver:   postgres
  host:     localhost
  port:     5432
  database: test
  username: test
  password: test123
  detail-log:     true
  max-open-conns: 100
  max-idle-conns: 10
server:
  port: :8888